server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/konnect_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          friendRequest: com.konnectnet.core.friend.event.FriendRequest
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          friendRequest: com.konnectnet.core.friend.event.FriendRequest

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 910508833594-ko7lnpm5rvir8sh8q9es0sgbu53blrla.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
logging:
  level:
    org.springframework.security.messaging: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.web: DEBUG

search:
  engine: lucene
  lucene:
    dir: ../lucene-index

